import type { RackItem } from "@/lib/data/racks";

const U_HEIGHT = 18;
const RACK_INNER_W = 460;
const LEFT_LABEL_W = 36;
const PADDING_X = 60;
const PADDING_TOP = 80;
const PADDING_BOTTOM = 110;

function escapeXML(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Render a rack layout as a printable, standalone SVG.
 * Black-on-white technical aesthetic — readable when printed.
 */
export function buildRackSVG(opts: {
  name: string;
  totalU: number;
  items: RackItem[];
  meta?: { project?: string | null; date?: Date | null };
}): string {
  const { name, totalU, items } = opts;
  const usedU = items.reduce((s, i) => s + i.uHeight, 0);
  const innerH = totalU * U_HEIGHT;
  const width = PADDING_X * 2 + LEFT_LABEL_W + RACK_INNER_W;
  const height = PADDING_TOP + innerH + PADDING_BOTTOM;

  const rackTop = PADDING_TOP;
  const rackLeft = PADDING_X + LEFT_LABEL_W;

  const parts: string[] = [];
  parts.push(
    `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" font-family="system-ui, -apple-system, Segoe UI, sans-serif">`
  );

  // background
  parts.push(`<rect width="100%" height="100%" fill="#ffffff"/>`);

  // Title block
  parts.push(
    `<text x="${PADDING_X}" y="34" font-size="14" font-weight="700" fill="#1a1a1a" letter-spacing="0.8">${escapeXML(name.toUpperCase())}</text>
    <text x="${PADDING_X}" y="52" font-size="10" fill="#737373">${escapeXML(`${totalU}U enclosure · ${usedU}U used · ${totalU - usedU}U free`)}</text>
    ${opts.meta?.project ? `<text x="${PADDING_X}" y="66" font-size="10" fill="#737373">Project: ${escapeXML(opts.meta.project)}</text>` : ""}`
  );

  // U labels (1 at bottom, totalU at top)
  for (let u = 1; u <= totalU; u++) {
    const y = rackTop + innerH - (u - 1) * U_HEIGHT - U_HEIGHT / 2;
    parts.push(
      `<text x="${PADDING_X + LEFT_LABEL_W - 6}" y="${y + 3}" text-anchor="end" font-size="8" font-family="ui-monospace, monospace" fill="#a3a3a3">${u}</text>`
    );
  }

  // Rack frame
  parts.push(
    `<rect x="${rackLeft}" y="${rackTop}" width="${RACK_INNER_W}" height="${innerH}" fill="#fafafa" stroke="#1a1a1a" stroke-width="1.5"/>
    <rect x="${rackLeft + 4}" y="${rackTop}" width="2" height="${innerH}" fill="#d4d4d4"/>
    <rect x="${rackLeft + RACK_INNER_W - 6}" y="${rackTop}" width="2" height="${innerH}" fill="#d4d4d4"/>`
  );

  // U row dividers (subtle)
  for (let u = 1; u < totalU; u++) {
    const y = rackTop + u * U_HEIGHT;
    parts.push(
      `<line x1="${rackLeft}" y1="${y}" x2="${rackLeft + RACK_INNER_W}" y2="${y}" stroke="rgba(0,0,0,0.05)" stroke-width="0.5"/>`
    );
  }

  // Items
  for (const it of items) {
    const itemY = rackTop + innerH - (it.uStart - 1) * U_HEIGHT - it.uHeight * U_HEIGHT;
    parts.push(
      `<rect x="${rackLeft + 10}" y="${itemY + 2}" width="${RACK_INNER_W - 20}" height="${it.uHeight * U_HEIGHT - 4}" fill="#fff5eb" stroke="#ff6b00" stroke-width="1"/>
      <text x="${rackLeft + 16}" y="${itemY + (it.uHeight * U_HEIGHT) / 2 + 3}" font-size="9" font-family="ui-monospace, monospace" fill="#737373">U${it.uStart}-${it.uStart + it.uHeight - 1}</text>
      <text x="${rackLeft + 60}" y="${itemY + (it.uHeight * U_HEIGHT) / 2 + 3}" font-size="10" font-weight="600" fill="#1a1a1a">${escapeXML(it.label)}</text>`
    );
  }

  // Legend / footer
  const footerY = rackTop + innerH + 30;
  parts.push(
    `<line x1="${PADDING_X}" y1="${footerY}" x2="${width - PADDING_X}" y2="${footerY}" stroke="#e5e5e5"/>
    <text x="${PADDING_X}" y="${footerY + 18}" font-size="9" font-weight="700" fill="#1a1a1a" letter-spacing="1">ELEVATION SCHEDULE</text>
    <text x="${PADDING_X}" y="${footerY + 34}" font-size="9" fill="#525252">${items.length} items · Generated by ZynexAV CRM · ${new Date().toLocaleDateString()}</text>`
  );

  parts.push(`</svg>`);
  return parts.join("\n");
}
